version: '3'
services:
  telebot:
    build: .
    container_name: telebot
    restart: on-failure
    volumes:
      - ./:/filter
    command: python3 telegram-bot.py
  flask:
    build: .
    container_name: filters
    environment:
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./:/filter
    ports:
      - "5000:5000"
    command: python3 app.py